version: "3"

services:
  crypto-trading:
    build: .
    container_name: binance_trader
    volumes:
    - ./user.cfg:/app/user.cfg
    - ./data:/app/data
    ports:
    - 8000:8000

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
      - ./data:/data
    ports:
      - 3000:3000
