version: "3"

services:
  crypto-trading:
    build: .
    image: binance_trader
    container_name: binance_trader
    volumes:
    - ./user.cfg:/app/user.cfg
    - ./data:/app/data
    command: python crypto_trading.py

  api:
    depends_on:
      - crypto-trading
    image: binance_trader
    container_name: binance_trader_api
    volumes:
      - ./data:/app/data
    ports:
      - 5123:5123
    command: gunicorn api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
      - ./data:/data
    ports:
      - 3000:3000
